# Generated by Django 4.0.6 on 2022-11-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_photo_remove_album_belonger'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.album'),
        ),
    ]
